sudo: required

language: go

go:
  - 1.6
  - tip

branches:
  only: [master]

services:
  - docker

env:
  - DOCKERTEST_BIND_LOCALHOST=true

script:
  - go vet $(go list ./... | grep -v '/vendor/')
  - go test -v $(go list ./... | grep -v '/vendor/')