sudo: false

language: go

go:
  - "1.9.4"

branches:
  only: [master]

services:
  - docker

script:
  - go vet $(go list ./... | grep -v '/vendor/')
  - go test -v $(go list ./... | grep -v '/vendor/')